language: python
python: 3.7
jobs:
  include:
    - if: branch = master
      python: 2.7
      env: TOXENV=py27-master
      after_success: codecov
    - if: branch = master
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master
      python: 2.7
      env: TOXENV=py27-dev
      after_success: codecov
    - if: branch != master
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
    - env: TOXENV=pre-commit
    - stage: Deploy to Test PyPI release
      env: TOXENV=build
      before_script: sed -i -E "s/^([0-9]+\.[0-9]+\.[0-9]+)$/\1.$TRAVIS_BUILD_NUMBER/" version.txt
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: "__token__"
        password:
          secure: "KahwCiio9LH/oFleuT7hyfJ3dhq3TwtAjY9VGIFbZ0wsP4St7tyThT3iU6rulN6jlowKACfjL6kDoJ+PIFjtZqCYvnzdmJeXiqiEGhSEP3N+aIlKuq5PZ7vyPem7Z7SAtpXKaiHmwZ5gmWjT4A3EWkNscyF0PauIKDvmsWNZ2fCjAdhUE8yD2TrE6TlCKp7sdBgqlCqxd8NAsjcQIa7HMvLi427QB0DhhUxPBcg0TRBCbj6mRkyS2onf2tFXj7PVNeVOkTO2p0Gkwp2zuli9WxySN0Q91YIbUUIFyxOw7OClXqLy8zWaUfkwnKnL4sQHcKmO8G2rpOloRIprLbRGe6Fzn55EerHkCVJewIdmlxsvL6Qsm87gMc5QqgxduPiB717gRThoTwfpoVhv4uZuW7vlDL7R9seADPRyk0O9isfmFpqk6eyMz3vbAqqFpzfAAV9MEwi/YGlZlBOqkzZjXcecS9YXxuTpReqLYG3Q9vNflTBXiXMhLRz09MUkSyzy3QYpnraW5aigWHVR7LY8G8Rf9TW6kPTLaELgH7vC8REyqWHUO2ON/uGVfmsEzXMKf3+d9FA3ULstLr+dwSj2p/6VlxKdSSopydW7T9zxuk4G0kyFak7+XXuL5WWHDcDIHSgRjMHijSxdaLTWwHquHioWiP5Ga93hwUsmsCX2r8A="
        on:
          branch: dev
    - stage: Deploy to PyPI release
      env: TOXENV=build
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        password:
          secure: "wFUD2q1Xf+4nGIt2DwPB5CRbGAdcBYzZ4PIms72TiCiX6qqVwrJ85EXgL6uJ3RdBcLt24efMq0VZhqKVn1kcQz872pNBRbJpYr3t3k8tUFcEs8ylsef7gQIuqohiuQovUmkrg8ET3i7QOjrRFfsR3nPOGWmNsl5DfDxdE3zXKcTBZ4hmEoEV1v5/xP9PS6YJhkflI+QqdFWFAWz5PKX04CF+iqwXZRONM18hlzkmhXOj44BUU/1EOOFHuRczKlnl7VBUfT5RCDG4eAkLRjXoiX+6G3XUY/ieQo54cGr0ESe+LWz2eniJ5/vJkf15Vpd28cUx2t6JeI/1j37Fhkmbg6oXQ5ElL3bdxCWRDfD6cNsgCNSkef2SRbldOHUQFatpxFai7GzV3CO6D/+dHnh6HdSEBCU9t6aZyTdaIA7JZzECsDSwHsZHKqKR1eCYIdLwZcvUl91WNk8qi8R/Ik5rTZyGt7DCgWIUoKU6kxqqQO3h9mlQrIdmqYd90nTj+Ne0ZT/TqAEOKbme6n8O198vv82DXRipQqAVqMeieENCXBP0DfrYo3TnpOvR0gz8DoE6+O2/JzlbygPkQRJOHcFfLkPP7T4J4R6z8YLi8QsI+KyXniCT7EjDYPXjPPJIU3JLBbAynT+D9upEwFYitWDExRj4y2rk3GyMZCp6IZAnBZ0="
        on:
          tags: true
    - stage: Create GitHub release
      env: TOXENV=build
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - export GIT_TAG="$(cat version.txt | tr -d ' \t\n\r')"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $GIT_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: "jLdiPdwQmAlLKO26B7hS4UhCNbZG8ybmjGZRZ+9Dmp2aT+D84jdBpbn0UfQJYP1yAl6tzcxqDagVsnGehEWwGZiVag/4Qxg090hUAJ31VjxW669cyN9ZRMreuhCMeS3etI39e/5tR8Lud/LzI40tPNYGcQvS+RRBIDGuQIPnPNaNJ42GPeyNKIrpS2+JrypWtHHrl537fvX7F4NK2KXFIBm+C9HhuGK1AfHD+UU8ReeysvRYnZh9B6JQnIHUiDy28kUrLq1fD4TO7x79wiAW+Wrvzn2XsbjMJyL4AbxxXHMLY8Am49vjtktAFuVKYdfPZS0tMB7OS7Y0HOT04KMzEDLtPEFGlVIMdZ1V8UCLC/gHpBpPdfKg4+BcoYvwg4afuFF76fmDDbm0IQY7p0E3nOqdwjprFfG5bqX0Qb4UXAHtzbmNrn/FE1BibA7EvX0zglTB2eGuNGwa617JK/Pt6iZVmo/lSwALl2E9EMP3kbez/Q9seUYyxXyIT0M4OyvE9AOgGNG5QDRvD/NHMjnWo/Q0KOCV6Q51BnYRLIUhKHw5aPtFQ13u6hgJGPE/769ca5Gxopary8CKjWDvEuMVa+vLyCZ+9jiGpfToWNqV9kC8pq5EcsG4BqxHVogNbb/XZLAGteLYU1IETOSiK65v+9OnGJ67Z0gP5iiVz76OqJA="
        file_glob: true
        file: dist/*
        name: cloudshell-snmp-autoload $GIT_TAG
        target_commitish: master
        on:
          branch: master
    - stage: Check version
      language: bash
      install:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! git diff --exit-code --quiet origin/master version.txt"

install:
  - pip install tox
  - pip install codecov

script: tox

stages:
  - name: Check version
    if: branch = master AND type = pull_request
  - name: Test
  - name: Deploy to Test PyPI release
    if: branch = dev AND type != pull_request
  - name: Create GitHub release
    if: branch = master AND type != pull_request
  - name: Deploy to PyPI release
    if: tag IS present